# Generated by Django 5.1.3 on 2024-12-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table='exam',
        ),
    ]
