# Generated by Django 5.1.3 on 2024-12-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_question_contact_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('email', '이메일'), ('openchat', '오픈 채팅'), ('hywtalk', '하이유톡'), ('contact_etc', '기타(글로 작성해 주세요.)')], max_length=20, null=True, verbose_name='연락 수단'),
        ),
        migrations.AlterField(
            model_name='question',
            name='desired_language',
            field=models.CharField(blank=True, choices=[('english', '영어'), ('chinese', '중국어'), ('japanese', '일본어'), ('language_etc', '기타(글로 작성해 주세요.)')], max_length=50, null=True, verbose_name='희망 언어'),
        ),
        migrations.AlterField(
            model_name='question',
            name='location',
            field=models.CharField(blank=True, choices=[('library', '도서관'), ('cafe', '카페'), ('studyroom', '스터디 룸 (도서관)'), ('classroom', '강의실'), ('location_etc', '기타(글로 작성해 주세요.)')], max_length=20, null=True, verbose_name='희망 장소'),
        ),
        migrations.AlterField(
            model_name='question',
            name='online_offline',
            field=models.CharField(blank=True, choices=[('online', '온라인'), ('offline', '오프라인')], max_length=10, null=True, verbose_name='온/오프라인'),
        ),
        migrations.AlterField(
            model_name='question',
            name='preferred_day',
            field=models.CharField(blank=True, choices=[('monday', '월요일'), ('tuesday', '화요일'), ('wednesday', '수요일'), ('thursday', '목요일'), ('friday', '금요일'), ('saturday', '토요일'), ('sunday', '일요일'), ('day_etc', '기타(글로 작성해 주세요.)')], max_length=20, null=True, verbose_name='희망 요일'),
        ),
        migrations.AlterField(
            model_name='question',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('am', '오전'), ('pm', '오후'), ('after', '수업 마친 후'), ('before', '수업 전'), ('time_etc', '기타(글로 작성해 주세요.)')], max_length=20, null=True, verbose_name='희망 시간'),
        ),
        migrations.AlterField(
            model_name='question',
            name='target',
            field=models.CharField(blank=True, choices=[('TOEIC', 'TOEIC'), ('TOEIC4', 'TOEIC 400점대'), ('TOEIC5', 'TOEIC 500점대'), ('TOEIC6', 'TOEIC 600점대'), ('TOEIC7', 'TOEIC 700점대'), ('TOEIC8', 'TOEIC 800점대'), ('TOEIC9', 'TOEIC 900점대'), ('TOEICNEW', 'TOEIC 입문'), ('JLPT', 'JLPT'), ('JLPT5', 'JLPT N5'), ('JLPT4', 'JLPT N4'), ('JLPT3', 'JLPT N3'), ('JLPT2', 'JLPT N2'), ('JLPT1', 'JLPT N1'), ('JLPTNEW', 'JLPT 입문'), ('HSK', 'HSK'), ('HSK1', 'HSK 1급'), ('HSK2', 'HSK 2급'), ('HSK3', 'HSK 3급'), ('HSK4', 'HSK 4급'), ('HSK5', 'HSK 5급'), ('HSK6', 'HSK 6급'), ('HSKNEW', 'HSK 입문'), ('target_etc', '기타(글로 작성해 주세요.)'), ('nothing', '없음')], max_length=50, null=True, verbose_name='목표 설정'),
        ),
    ]
