# Generated by Django 5.1.3 on 2024-12-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_question_contact_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='calendar_link',
            field=models.URLField(blank=True, null=True, verbose_name='캘린더 링크'),
        ),
        migrations.AddField(
            model_name='question',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='연락 정보'),
        ),
    ]
